name: PHP Composer

on:
  push:
    branches: [ "master" ]
  

permissions:
  contents: read

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    
    - name: Run test suite
      run: cd /var/www/html/test2 && git pull origin master && composer install
   
      

    

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
